services:
  # Django service
  web:
    build:
      context: .  # Path to the directory containing your Dockerfile
    command: |
      bash -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/app  # Mount the app directory into the container
      - ./media:/app/media  # Mount the media folder to persist data
    env_file:
      - .env  # Load environment variables from the .env file
    ports:
      - "8000:8000"  # Expose port 8000 for Django
    networks:
      - app_network

  # Nginx service
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Custom Nginx config
      - ./media:/app/media  # Volume the media folder
      - ./static:/app/static  # Mount static files to serve them from the host
    ports:
      - "8080:80"  # Expose port 80 for HTTP
    depends_on:
      - web
    networks:
      - app_network

  # MINIO service
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_USERNAME}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    volumes:
      - minio_data:/data
    command: server --compat /data --console-address ":9001"
    networks:
      - app_network

volumes:
  minio_data:

networks:
  app_network: