services:
  # Django service
  # gunicorn config.wsgi:application --bind 0.0.0.0:8000
  # daphne -b 0.0.0.0 -p 8000 config.asgi:application
  web:
    build:
      context: .  # Path to the directory containing your Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    volumes:
      - .:/app  # Mount the app directory into the container
      - ./media:/app/media
      - ./logs.log:/app/logs.log
    env_file:
      - .env  # Load environment variables from the .env file
    ports:
      - "8008:8000"  # Expose port 8000 for Django
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Nginx service
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Custom Nginx config
      - ./media:/app/media  # Volume the media folder
      - ./static:/app/static  # Mount static files to serve them from the host
    ports:
      - "8080:80"  # Expose port 80 for HTTP
    depends_on:
      - web
    networks:
      - app_network


  redis:
    image: redis:6-alpine
    restart: always
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "5002:8081"

  celery:
    build:
      context: .
    entrypoint: [ "/bin/sh", "-c", "celery -A config worker" ]
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - web

  celery-beat:
    build:
      context: .
    entrypoint: [ "/bin/sh", "-c", "celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler" ]
    env_file:
      - .env

  flower:
    image: mher/flower:0.9.7
    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    ports:
      - "5001:5555"
    environment:
      CELERY_BROKER_URL: ${BROKER_URL}
    depends_on:
      - redis
      - celery


  # MINIO service
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_USERNAME}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    volumes:
      - ./minio_data:/data
    command: server --compat /data --console-address ":9001"
    networks:
      - app_network

volumes:
  minio_data:

networks:
  app_network: