# Generated by Django 5.2 on 2025-04-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsconfirmation',
            name='purpose',
            field=models.CharField(choices=[('login', 'Регистрация'), ('forgot_password', 'Забыли пароль'), ('password_reset', 'Сброс пароля'), ('phone_update', 'Обновление телефона'), ('delete_account', 'Удаление аккаунта')], max_length=20),
        ),
    ]
