# Generated by Django 5.2 on 2025-08-23 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_donation_is_active'),
        ('integrations', '0011_multibanktransaction_creator_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multibanktransaction',
            name='callback_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='multibanktransaction',
            name='donation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multibank_transactions', to='authentication.donation'),
        ),
        migrations.AddField(
            model_name='multibanktransaction',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multibank_transactions', to='authentication.usersubscription'),
        ),
    ]
