# Generated by Django 5.2 on 2025-09-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_multibanktransaction_callback_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multibanktransaction',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('card', 'Карта'), ('click', 'Click'), ('payme', 'Payme')], default='card', null=True),
        ),
    ]
