# Generated by Django 5.2 on 2025-09-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_multibanktransaction_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='multibanktransaction',
            name='ofd_items',
            field=models.JSONField(null=True),
        ),
    ]
