# Generated by Django 5.2 on 2025-07-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_post_is_blocked_reportcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='block_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='block_reason',
            field=models.CharField(choices=[('copyright', 'Контент, нарушающий авторские права третьих лиц'), ('extremism', 'Материалы экстремистского, террористического характера'), ('discrimination', 'Дискриминация по расовому, половому, религиозному и другим признакам'), ('pornography', 'Порнографические материалы и контент для взрослых'), ('violence', 'Агрессивный, жестокий или призывающий к насилию контент'), ('drugs_alcohol', 'Призывы к употреблению наркотических веществ и алкоголя'), ('misleading', 'Введение пользователей в заблуждение (мошенничество, спам, фейковые сборы средств)'), ('personal_data', 'Контент, содержащий личные данные третьих лиц без их согласия'), ('other', 'Другое')], max_length=20, null=True),
        ),
    ]
