# Generated by Django 5.2 on 2025-04-27 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='questionnaire_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.post'),
        ),
        migrations.AlterModelTable(
            name='answeroption',
            table='post_questionnaire_answer',
        ),
    ]
