# Generated by Django 5.2 on 2025-07-18 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_post_block_desc_post_block_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcomment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to='content.report'),
        ),
    ]
