# Generated by Django 5.2 on 2025-04-30 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_category_user_creator_description'),
        ('content', '0005_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='authentication.subscription'),
        ),
    ]
