# Generated by Django 5.2 on 2025-04-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_post_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
