# Generated by Django 5.2 on 2025-08-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_category_name_en_category_name_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
