# Generated by Django 5.2 on 2025-05-05 08:40

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_report_unique_together_post_is_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publication_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PostSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('post_publication', 'Post Publication')], default='post_publication', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('execute_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='content.post')),
            ],
            options={
                'ordering': ['execute_at', '-priority'],
                'indexes': [models.Index(fields=['status', 'execute_at'], name='content_pos_status_7e5f8c_idx'), models.Index(fields=['task_type', 'status'], name='content_pos_task_ty_86a02e_idx'), models.Index(fields=['post'], name='content_pos_post_id_06b011_idx')],
            },
        ),
    ]
