# Generated by Django 5.2 on 2025-05-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_post_publication_time_postschedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postschedule',
            new_name='post_schedu_status_8bd891_idx',
            old_name='content_pos_status_7e5f8c_idx',
        ),
        migrations.RenameIndex(
            model_name='postschedule',
            new_name='post_schedu_task_ty_afd74c_idx',
            old_name='content_pos_task_ty_86a02e_idx',
        ),
        migrations.RenameIndex(
            model_name='postschedule',
            new_name='post_schedu_post_id_d84f8e_idx',
            old_name='content_pos_post_id_06b011_idx',
        ),
        migrations.AlterField(
            model_name='postschedule',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterModelTable(
            name='postschedule',
            table='post_schedule',
        ),
    ]
