# Generated by Django 5.2 on 2025-04-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sms_verified',
            field=models.BooleanField(default=False),
        ),
    ]
