# Generated by Django 5.2 on 2025-05-22 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('donation', 'Задонатил'), ('commented', 'Оставил комментарий'), ('followed', 'Фолловнул'), ('subscribed', 'Подписался'), ('liked', 'Лайкнул')], max_length=10)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_id', models.CharField(blank=True, max_length=50, null=True)),
                ('content_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_owner', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_initiator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activity',
            },
        ),
    ]
