# Generated by Django 5.2 on 2025-04-29 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_subscription'),
        ('content', '0005_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='content.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='creator_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
