# Generated by Django 5.2 on 2025-05-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='type',
            field=models.CharField(choices=[('donation', 'Задонатил'), ('commented', 'Оставил комментарий'), ('replied', 'Оставил ответный комментарий'), ('followed', 'Фолловнул'), ('subscribed', 'Подписался'), ('liked_post', 'Лайкнул пост'), ('liked_comment', 'Лайкнул комментарий')], max_length=20),
        ),
    ]
