# Generated by Django 5.2 on 2025-05-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_subscription_banner_remove_subscription_user_and_more'),
        ('content', '0009_alter_report_unique_together_post_is_premium_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['follower'], name='user_follow_followe_e438c6_idx'),
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['followed'], name='user_follow_followe_e01db9_idx'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.UniqueConstraint(fields=('follower', 'followed'), name='followers_unique_followed_follower'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(fields=('subscriber', 'creator'), name='user_subs_unique_subscriber_creator'),
        ),
    ]
