# Generated by Django 5.2 on 2025-05-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_delete_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cvc_cvv',
            field=models.CharField(default=123, max_length=5),
            preserve_default=False,
        ),
    ]
