# Generated by Django 5.2 on 2025-05-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_card_cvc_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvc_cvv',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
