# Generated by Django 5.2 on 2025-05-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_card_cvc_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
