# Generated by Django 5.2 on 2025-05-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_subscriptionplan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration',
            field=models.CharField(max_length=5),
        ),
    ]
