# Generated by Django 5.2 on 2025-05-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_card_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='payment_reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
