# Generated by Django 5.2 on 2025-05-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_usersubscription_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='commission_by_subscriber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('card', 'Карта'), ('click', 'Click'), ('payme', 'Payme')], default='card', null=True),
        ),
    ]
