# Generated by Django 5.2 on 2025-05-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_usersubscription_commission_by_subscriber_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usersubscription',
            name='user_subs_unique_subscriber_creator',
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(fields=('subscriber', 'creator', 'plan'), name='user_subs_unique_subscriber_creator_plan'),
        ),
    ]
