# Generated by Django 5.2 on 2025-05-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_chatroom_message_blockeduser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='BlockedUser',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
