# Generated by Django 5.2 on 2025-07-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_remove_notificationdistribution_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='commission_by_subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
