# Generated by Django 5.2 on 2025-07-13 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_donation_commission_by_subscriber'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='donation_banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_banner', to='files.file'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_donation_letters',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_donation_amount',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
    ]
