# Generated by Django 5.2 on 2025-07-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_alter_card_expiration_alter_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='multibank_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
