# Generated by Django 5.2 on 2025-08-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_card_multibank_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
