# Generated by Django 5.2 on 2025-08-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_donation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='one_time',
            field=models.BooleanField(default=False),
        ),
    ]
