# Generated by Django 5.2 on 2025-10-14 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_donation_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='subscriber_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='authentication.card'),
        ),
    ]
