# Generated by Django 5.2 on 2025-10-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0037_alter_usersubscription_subscriber_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
