# Generated by Django 5.2 on 2025-10-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0038_usersubscription_is_paid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usersubscription',
            name='user_subs_unique_subscriber_creator_plan',
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_paid', True)), fields=('subscriber', 'creator', 'plan'), name='user_subs_unique_subscriber_creator_plan'),
        ),
    ]
