# Generated by Django 5.2 on 2025-08-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatsettings_minimum_message_donation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(blank=True, choices=[('message', 'Сообщение'), ('file', 'Файл'), ('media', 'Медиа')], default='message', max_length=55, null=True),
        ),
    ]
